### ISSUE TITLE
Stacker is not updating with CF's status

### ISSUE THREAD

**Issue by maraca** [cotap/stacker#21]
I've observed that recently stacker ends up repeating `CREATE_IN_PROGRESS` and does not actually read the latest update from CloudFormation. For example here the stack has been created however stacker does not change its status to `CREATE_COMPLETE`.
It will loop until I hit `Ctrl+c`.

![screen shot 2016-07-11 at 11 05 56 am](https://cloud.githubusercontent.com/assets/374087/16741316/97f0e3d0-4757-11e6-98c3-1c006d110abf.png)
@jfhamlin @kainosnoema @eyeamera, are you guys experiencing the same issue?

**Comment by jfhamlin** [comment]
Yep, I've seen the same. Would be great to get this fixed or even enhance the status log.

**Comment by kainosnoema** [comment]
@maraca will go for scotch in a separate PR.
